metrics:
  provider: prometheus
  options:
    host: "0.0.0.0"
    port: 9100
    default_labels:
      environment: "prod"
    otel:
      enabled: true
      endpoint: "otel-collector.prod.svc.cluster.local:4317"

